### ISSUE TITLE
Upgrade to CLDR 44

### ISSUE THREAD

**Issue by tomasr8** [python-babel/babel#1070]
CLDR v44 has been released a while ago. Are there any plans to include it in babel?

**Comment by ThiefMaster** [comment]
v45 is [scheduled](https://docs.google.com/spreadsheets/d/1N6inI5R84UoYlRwuCNPBOAP7ri4q2CmJmh8DC5g-S6c/edit#gid=1680747936) to be released in less than a week. Maybe best to aim for that straight away?

**Comment by akx** [comment]
#1071 bumps us up to CLDR 44. Cc @nileshpatra via https://github.com/python-babel/babel/issues/1059#issuecomment-1979589995 – would it be useful for e.g. Debian that there'd be a Babel version that uses CLDR 44, even if CLDR 45 is released soon?

**Comment by nileshpatra** [comment]
On Mon, Apr 15, 2024 at 07:12:43AM -0700, Aarni Koskela wrote:
> #1071 bumps us up to CLDR 44. Cc @nileshpatra via https://github.com/python-babel/babel/issues/1059#issuecomment-1979589995 – would it be useful for e.g. Debian that there'd be a Babel version that uses CLDR 44, even if CLDR 45 is released soon?

I am not sure if I understand that question. Currently CLDR version in Debian is
44 - which is what we need. It probably will be upgraded to 45 at some point.

> That said, the next version of Babel will not officially support Python 3.7 anymore; is that an issue?

No problem.

**Comment by akx** [comment]
> I am not sure if I understand that question. Currently CLDR version in Debian is 44 - which is what we need.

Right, so I think it'll be a good idea to release a version of Babel that basically just bumps up to CLDR 44, just so that version can be easily shipped with the version of Debian that targets CLDR 44.

> It probably will be upgraded to 45 at some point.

As far as I understand Debian's stability/release process, that might not be in the immediate cards as soon as 45 is released, though? :)

**Comment by nileshpatra** [comment]
On 15 April 2024 9:57:06 pm IST, Aarni Koskela ***@***.***> wrote:
>> I am not sure if I understand that question. Currently CLDR version in Debian is 44 - which is what we need.
>
>Right, so I think it'll be a good idea to release a version of Babel that basically just bumps up to CLDR 44, just so that version can be easily shipped with the version of Debian that targets CLDR 44.
>
>> It probably will be upgraded to 45 at some point.
>
>As far as I understand Debian's stability/release process, that might not be in the immediate cards as soon as 45 is released, though? :)

I apologise if I wasn't clear w/ my bug report earlier. Babel is doing fine in debian stable release (which happens roughly every 1.5-2 years) and has cldr version 41.

The cldr version is 44 in current unstable/testing which will be the next stable release around an year from now. cldr maybe updated to 45 in a few months or so since there's still an year in the next Debian stable release. As such there's no set target yet. If you plan to upgrade to 45, you could do so -- I'll apply the relevant patches.

**Comment by akx** [comment]
The freshly released Babel 2.15.0 ([GH](https://github.com/python-babel/babel/releases/tag/v2.15.0), [PyPI](https://pypi.org/project/Babel/2.15.0/)) is backed by CLDR 44.
