### ISSUE TITLE
format_currency with Japanese JPY does not shave decimals

### ISSUE THREAD

**Issue by achuinard** [python-babel/babel#139]
It is to my understanding that the Japanese Yen (JPY) does not use decimal places. Therefore, I'd say if I passed in a decimal to format_currency, and used ja_JP for the locale as well as JPY for the currency, I should get that decimal rounded.

Am I doing something wrong?

**Comment by benselme** [comment]
You aren't doing anything wrong but this is not supported yet as far as I can tell. 

Proper support for this would mean extracting currencyData/fractions data in CLDR's `supplementalData.xml` and then using it in `format_currency`.

**Comment by achuinard** [comment]
If you could point me into where to start / look in the code and integrate this, I think I'll fork it and give it a try.

**Comment by benselme** [comment]
Sure. The first step would be to import the data from the CLDR file. This happens in `scripts/import_cldr.py`. You'll need to understand what the data in the xml file means exactly, the specs for these elements are located here: http://www.unicode.org/reports/tr35/tr35-37/tr35-numbers.html#Supplemental_Currency_Data
Once you have imported the data, it's accessible through the `get_global` function. 
Then you can modify `format_currency` to apply proper rounding where appropriate.

**Comment by benselme** [comment]
Looks like some work was done in #120 but then the author closed the PR.

**Comment by achuinard** [comment]
I'm a little discouraged from doing the work as it seems the project has been almost abandoned by the mitsuhiko. Why would a pull request like that just be 'closed'?

**Comment by benselme** [comment]
FWIW #120 was closed by its own author. 

But it's true that there hasn't been much activity recently and that PR and issues are piling up. I'm using my own fork in the meantime...

**Comment by etanol** [comment]
I don't remember know if I explicitly closed the pull request or GitHub did it when I renamed the branch.  I normally use Mercurial so I have a very hard time tyring to work with Git and GitHub.

Anyhow, I keep working on [this branch](https://github.com/etanol/babel/tree/roiback) when I need some fixes or improvements.  For instance, these days I'm trying to improve the performance of the currency formatter, as we hit a bottleneck there at work.  From time to time, I also check to see more attempts to upgrade to CLDR >= 26.

Armin seems to be currently more focused on Rust than on Python, so don't expect this repository to receive much attention.  It's a bit fo a pity, since he took over the previous maintainer precisely for the same reason.

Fortunately, this is open source, do as you please with it, just as I did.
