### ISSUE TITLE
How about a 2.1 release?

### ISSUE THREAD

**Issue by jrfern** [python-babel/babel#224]
This is just a reflexion, sort of an example of wishful thinking - take it as a question.

Release 2.0 was created in July. The important (at least for me) fix for the 2010 Language header (issue #76), which brought at least three PR's that I know of, was merged in August, so it's out of 2.0. I see work is being done for a 3.0 version some time in the future. Are intermediate releases planned? I would love to see an intermediate  2.1 release issued in the near future. Is that possible?

**Comment by sils1297** [comment]
Hey @jrfern thanks for bringing this explicitly to our attention. However we don't have access to pypi yet and I've not yet found a way to reach @mitsuhiko since quite some time via GitHub, Mail or IRC.

Related bug https://github.com/mitsuhiko/babel/issues/209 . Keeping this open so we'll do a 2.1 release as soon as we literally can.

**Comment by sils1297** [comment]
@jrfern however we did forget to backport #76 to the 2.x maintenance branch it seems. We'll do that soonish. Manpower's short :/

**Comment by sils1297** [comment]
I just merged the backport. Will do a 2.1 release todayish.

**Comment by sils1297** [comment]
Ok, what needs to be done:

- Update the CHANGES file to contain whatever we added since the last release. I hate this :P could someone do this for me? I have some other things on my plate right now.
- I want @erickwilder s consent that we want to release that.
- Then I'm doing the release ASAP, promised :)

**Comment by erickwilder** [comment]
@sils1297 
A new pull request was created with the `CHANGES` modifications: https://github.com/python-babel/babel/pull/251

**Comment by sils1297** [comment]
New Babel release available on https://pypi.python.org/pypi/Babel .

**Comment by haypo** [comment]
Hum, the version number 2.1.post20150925 is a suprising. Why not just Babel 2.1?

**Comment by sils1297** [comment]
This is my fault and I didn't have time to correct it today morning. Still
it is a valid version number so I left it and I'll probably reupload the
same code with a fixed version todayish.

**Comment by sils1297** [comment]
The post release version number problem was introduced in commit
2f8ed62038b42c8f228b7422ec18648bdc74d6c1 with the addition of the
`tag_date = true` setting which seems to trigger a post release for
whatever I'm doing. I'll change this to avoid those problems in the
future.

2015-09-25 13:08 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
> This is my fault and I didn't have time to correct it today morning. Still
> it is a valid version number so I left it and I'll probably reupload the
> same code with a fixed version todayish.
>

**Comment by sils1297** [comment]
I'll be doing a 2.1.1 release soon because of
https://github.com/python-babel/babel/issues/255 , this will make sure
everyone gets the right release for sure and nobody is confused with
any post prefixes (although they are specified in pep 0440).

2015-09-25 13:40 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
> The post release version number problem was introduced in commit
> 2f8ed62038b42c8f228b7422ec18648bdc74d6c1 with the addition of the
> `tag_date = true` setting which seems to trigger a post release for
> whatever I'm doing. I'll change this to avoid those problems in the
> future.
>
> 2015-09-25 13:08 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
>> This is my fault and I didn't have time to correct it today morning. Still
>> it is a valid version number so I left it and I'll probably reupload the
>> same code with a fixed version todayish.
>>

**Comment by sils1297** [comment]
Release done. Sorry for all the confusion.
