### ISSUE TITLE
format_datetime using 'S...S' format is incorrect

### ISSUE THREAD

**Issue by bfordham-ubnt** [python-babel/babel#350]
When using a format string for format_datetime or format_time using microseconds 'S...', the displayed results are **always** incorrect if the datetime's microseconds has less than 5 digits.

```python
from datetime import datetime
d = datetime(2016, 2, 15, 8, 3, 1, 799)
print format_datetime(d, 's.S')
>>> 1.8       #should be 1.0
print format_datetime(d, 's.SSSS')
>>> 1.7990   # should be 1.0008
```

in babel.dates
```python
def format_frac_seconds(self, num):
        value = str(self.value.microsecond)
        return self.format(round(float('.%s' % value), num) * 10**num, num)
```
should be something like

```python
def format_frac_seconds(self, num):
        value = self.value.microsecond // 1000000
        return self.format(round(value, num) * 10**num, num)
```

**Comment by akx** [comment]
@bfordham-ubnt Thanks for the bug report! Since you already have the relevant patch (I took the liberty of adding the proper markup around it) in the issue here, would you be interested in writing a pull request too? If you don't have the time or inclination, it's fine too; just say so, and someone'll pick this up eventually. :)

**Comment by iamshubh22** [comment]
@bfordham-ubnt I would want to work on this.

**Comment by akx** [comment]
@iamshubh22 Go right ahead! :)

**Comment by akx** [comment]
Marking as in progress for @iamshubh22. (I'm unable to set @iamshubh22 as the assignee for the issue,  but anyway.)
