### ISSUE TITLE
pybabel extract forgot the -s CLI flag in version 2.3

### ISSUE THREAD

**Issue by paxswill** [python-babel/babel#390]
# Overview Description
The -s flag for pybable extract was a shorthand form of --strip-comments. As part of #311 the shorthand form was removed.

# Steps to Reproduce

1. Try to run `pybabel extract -s`

# Actual Results

    $ pybabel extract -s
    Usage: pybabel extract [options] <input-paths>
    
    pybabel: error: no such option: -s

# Expected Results

    $ pybabel extract -s
    Usage: pybabel extract [options] dir1 <dir2> ...
    
    pybabel: error: incorrect number of arguments

# Reproducibility

Introduced with v2.3 with the consolidation of the CLI interfaces.

**Comment by akx** [comment]
Thank you for the excellent bug report, @paxswill!

I added a fix (a rather short one :) ) for this to #389, and took a look at all the other parameters that the CLI might have forgotten (and it turns out it had).

Either way, we should have a fix for this in soon, and hopefully a bugfix release rolled out soon after.
