### ISSUE TITLE
Wrong week number for russian dates

### ISSUE THREAD

**Issue by suvit** [python-babel/babel#485]
Must be 2016-52 like de_DE locale
```
>>> import babel
>>> import datetime
>>> v = datetime.date(2017, 1, 1)
>>> babel.dates.format_date(v, format='YYYY-ww',locale='ru_RU')
u'2017-01'
>>> babel.dates.format_date(v, format='YYYY-ww',locale='de_DE')
u'2016-52'
```

**Comment by akx** [comment]
Hi @suvit! 

I verified that the behavior occurs with both Babel 2.3.x (CLDR 28) and Babel 2.4 (CLDR 29) as well as the currently-in-PR CLDR 30 branch, so it's not a CLDR version issue. :)

Either way this is an issue in the CLDR data, not Babel itself, and as such, we can't do much about fixing it. :(

However, digging deeper, this seems to be caused by the `ru` locale claiming having only one day in a week is enough for it to count as a week (see `locale-min_week_days`):

```
ru_RU 2017-01 {'locale-first_weekday': 0, 'locale-min_week_days': 1}
de_DE 2016-52 {'locale-first_weekday': 0, 'locale-min_week_days': 4}
```

In the [CLDR data](http://www.unicode.org/repos/cldr/trunk/common/supplemental/supplementalData.xml), this is represented here:
```xml
<minDays count="1" territories="001 GU UM US VI"/>
<minDays count="4" territories="AD AN AT AX BE BG CH CZ DE DK EE ES FI FJ FO FR GB GF GG GI GP GR HU IE IM IS IT JE LI LT LU MC MQ NL NO PL PT RE SE SJ SK SM VA"/>
```
`001` is the pseudo-territory "global"; you can see `DE` is in the 4-day list, but `RU` is not.

Do you have any references (in Russian or otherwise) that would verify that RU should be in the 4-day list?

**Comment by suvit** [comment]
Do you accept Wikipedia page (sorry, page in russian)?
https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F#.D0.9A.D0.B0.D0.BB.D0.B5.D0.BD.D0.B4.D0.B0.D1.80.D0.BD.D0.B0.D1.8F_.D0.BD.D0.B5.D0.B4.D0.B5.D0.BB.D1.8F_.D0.B8_.D0.B5.D1.91_.D0.BD.D1.83.D0.BC.D0.B5.D1.80.D0.B0.D1.86.D0.B8.D1.8F

It is written that Russia supports ISO 8601

**Comment by akx** [comment]
Thanks! (Google Translate helped me get the gist of the Wikipedia article :) )

Can you file a ticket in the CLDR bug tracker at http://unicode.org/cldr/trac/newticket ?

**Comment by suvit** [comment]
Thank you!

**Comment by akx** [comment]
This has been [fixed upstream](http://unicode.org/cldr/trac/changeset/13512), and will be available in Babel once we reach CLDR v32.

**Comment by suvit** [comment]
Cool, thank you again!
