### ISSUE TITLE
"ValueError: expected only letters, got u'ko-kr'"

### ISSUE THREAD

**Issue by ajaeger** [python-babel/babel#489]
With Babel 2.4.0 we get:
 File "/home/jenkins/workspace/openstack-manuals-tox-doc-publishlang/.tox/venv/local/lib/python2.7/site-packages/babel/core.py", line 1093, in parse_locale
"ValueError: expected only letters, got u'ko-kr'"

This comes from using "ko-kr" as locale in  http://git.openstack.org/cgit/openstack/openstack-manuals/tree/doc/install-guide/source/locale/ko_KR/LC_MESSAGES/install-guide.po#n42

We didn't have this problem with earlier Babel releases.

Other places in Babel accept the '-' like https://github.com/python-babel/babel/blob/v2.4.0/tests/test_core.py#L100 - why not here as well and break existing files this way?

**Comment by akx** [comment]
Hi!

The default separator for `parse_locale()` is the underscore, so in your case the locale name should be `ko_KR`.

The location you linked, https://github.com/python-babel/babel/blob/v2.4.0/tests/test_core.py#L100, explicitly passes `sep='-'`, which is why it works.

The behavior of `parse_locale()` has not changed between 2.3.4 and 2.4.0; the last changes to that code are from 2008. :)

**Comment by ajaeger** [comment]
@akx, while parse_locale() has not changed,  https://github.com/python-babel/babel/commit/08b9c5e76e19ae610f28759a5cf37621ac2fb734 now parses the po file which did not happen before - and thus introduces the problem.

**Comment by akx** [comment]
Ahhh, right you are! Didn't think about that.

**Comment by akx** [comment]
I'll wait for a while before cutting 2.4.1, in case there are other bug reports.

**Comment by ajaeger** [comment]
Thanks a lot @akx !
