### ISSUE TITLE
Misleading doc of locale argument defaults

### ISSUE THREAD

**Issue by xmo-odoo** [python-babel/babel#542]
Looking at the API doc for e.g. [format_datetime](http://babel.pocoo.org/en/latest/api/dates.html#babel.dates.format_datetime), I just noticed that it states the default value for the `locale` parameter is `'en_US_POSIX'`. That is *very* misleading as it actually uses the result of `babel.core.default_locale('LC_TIME')` which may not be anything like `en_US_POSIX` (and just happens to be so on the machine which built the documentation).

This can be fixed by providing an explicit signature as first line of the docstring (which will replace the extracted one) but I don't know that this is the fix the project would expect.

Please advise.

**Comment by akx** [comment]
Hi,

Yeah, you're correct that that's kind of misleading :( An explicit signature would be fine.

To be honest – and this is probably something that'd need to be implemented in Babel 3 – I think `default_locale('LC_...')` should be a lazy object that checks the current value of the envvar whenever invoked; otherwise (i.e. currently) runtime changes to the envvar won't get properly applied anyway.

**Comment by xmo-odoo** [comment]
I created a PR with the explicit autofunction signature. Though it only fixes the functions of the first section (Date and Time Formatting) despite the doc having other functions with an LC_TIME parameter.
