### ISSUE TITLE
Belarusian Ruble outdated

### ISSUE THREAD

**Issue by timtroendle** [python-babel/babel#561]
[Belarus has a new ruble since 2016](https://en.wikipedia.org/wiki/Belarusian_ruble) with ISO 4217 code `BYN`. This new ruble is missing in the currency database.

Reproduce:
```Python
from datetime import date
from babel.numbers import get_territory_currencies

get_territory_currencies("BY", date(2015, 1, 1)) # returns ['BYR'], correct

get_territory_currencies("BY", date(2017, 1, 1)) # returns ['BYR'], not correct
```

**Comment by akx** [comment]
Hello!

The new currency is mentioned in the [release notes for CLDR 31](http://cldr.unicode.org/index/downloads/cldr-31):

> New currency code BYR.
 
Running the same code on the current `master` (1378a3d5e7f7f111ea7828ff7429f0abbb513700) (which uses CLDR 32) returns the expected output.

```python
>>> from datetime import date
>>> from babel.numbers import get_territory_currencies
>>> get_territory_currencies("BY", date(2015, 1, 1))
['BYR']
>>> get_territory_currencies("BY", date(2017, 1, 1))
['BYR', 'BYN']
```

So, you can expect this to be fixed in Babel 2.6 :)
