### ISSUE TITLE
`Locale.get_display_name` raises a cryptic `TypeError` with valid args

### ISSUE THREAD

**Issue by wjdp** [python-babel/babel#601]
# Overview Description

`Locale.get_display_name` raises a cryptic `TypeError` with valid args.

# Steps to Reproduce

1. Create environment with python3.6 and babel-2.6.0
2. Run

```
from babel.core import Locale
Locale.parse('fi_FI').get_display_name('kw_GB')
```

# Actual Results
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/tmp/babel-bug/env/lib/python3.6/site-packages/babel/core.py", line 392, in get_display_name
    retval += ' (%s)' % u', '.join(details)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

# Expected Results

Some interpretation of "Finish (Finland)"

# Reproducibility

Yes

**Comment by akx** [comment]
Hi!

Thanks for the bug report.

The root cause is that the `kw_GB` locale does not have language name information for `fi`, so https://github.com/python-babel/babel/blob/d2cf189ff0ce505b46191268c3cbdc4b130d8dd6/babel/core.py#L381 returns `None`. However, the `fi_FI` locale, being formatted, _does_ have a script/territory/variant specifier (`FI`), so Babel ends up attempting to add `' (Finland)'` to `None`, which understandably fails.

I'm not sure what the right course of action would be for Babel, though: should it just return None even if it possibly could format _something_, or should it fall back to something like `"fi (Finland)"`?

**Comment by wjdp** [comment]
I guessed it was probably because kw is obscure enough to not have this data (we're using it as a test locale anyway :smile:). My workaround was to catch the TypeError and return the `en_GB` variant instead.

1. Returning None would allow users to catch this and handle the error themselves.
2. If there was a concept of a fallback locale (en?) it could fallback to that, but would irritate if you wanted to fallback to another.
3. The 'fi (Finland)' approach is more default agnostic, but if an end user was to see this output I'd want to catch it and instead use a fallback locale which is harder to do if there isn't anything to catch.
