### ISSUE TITLE
mt.dat permission denied when installing

### ISSUE THREAD

**Issue by ba05** [python-babel/babel#653]
I'm getting a permission error with mt.dat when trying to install via conda. I think the file might be corrupt as my system does not let it extract from the package.

**Comment by akx** [comment]
Sorry to hear you're having trouble!

What platform is this on? Can you show us exactly the steps you're doing, with all errors as they appear?

**Comment by fischersean** [comment]
Renewing discussion because this has cropped up for me. I am on windows on a corporate computer and I am getting a permission denied via conda install but I do not believe it is babel's installation that is causing problems. For example, I am even unable to extract using winzip. Even using admin credentials I am unable to get the installation to proceed. If I were to guess I would say that the issue lies with the antivirus software flagging the mt.dat file as malicious. I have previously been able to install babel 2.6 which used cldr 33.


Is there any guesses as to why this file in particular is giving issues? Thanks.

**Comment by ba05** [comment]
Still having this issue on Win10:

`Downloading and Extracting Packages
babel-2.8.0          | 5.3 MB    | ############################################################################ | 100%

InvalidArchiveError("Error with archive C:\\Users\\Duser\\AppData\\Local\\Continuum\\anaconda3\\pkgs\\babel-2.8.0-py_0ua45wozm\\pkg-babel-2.8.0-py_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create '\\\\?\\C:\\Users\\Duser\\AppData\\Local\\Continuum\\anaconda3\\pkgs\\babel-2.8.0-py_0\\site-packages\\babel\\locale-data\\mt.dat'")`

If I had to guess it is an anti virus or something thinking the mt.dat file is bad. Is there anyway to edit the build it does not use the mt.dat?

**Comment by akx** [comment]
Sure, you can remove mt.dat (but you won't have language data for Maltese).

* Download the latest wheel (https://files.pythonhosted.org/packages/15/a1/522dccd23e5d2e47aed4b6a16795b8213e3272c7506e625f2425ad025a19/Babel-2.8.0-py2.py3-none-any.whl)
* Since wheels are just zip files, you can either
  * `zip Babel-2.8.0-py2.py3-none-any.whl -d babel/locale-data/mt.dat` if you have the `zip` tool
  * or rename it to .zip, remove `babel/locale-data/mt.dat`, and rename it back
* Install using e.g. `pip install ./Babel-2.8.0-py2.py3-none-any.whl`
