### ISSUE TITLE
No currency symbol for Icelandic crown (ISK)

### ISSUE THREAD

**Issue by mikazz** [python-babel/babel#780]
```
from decimal import Decimal
from babel.numbers import format_currency

x = format_currency(Decimal("1000.00"), 'ISK', locale='is_IS')
print(x)
# 1.000 ISK
```

Should return `kr.` instead of `ISK`

Reference:
https://en.wikipedia.org/wiki/Icelandic_kr%C3%B3na

**Comment by akx** [comment]
Hi there!

This is due to [`kr.` being still in `draft="contributed"`](https://st.unicode.org/cldr-apps/v#/is/C_NWEurope/70144d643e9787fe) status in CLDR data (which means not enough trusted CLDR reviewers have accepted it), and Babel does not, out of an abundance of caution, does not import any non-finalized data.
