### ISSUE TITLE
Distutils is deprecated and will be remove in python 3.12

### ISSUE THREAD

**Issue by RomainBrault** [python-babel/babel#824]
Distutils is used in many places.

Is there any hope that Babel will work with python 3.12?

See:

- https://docs.python.org/fr/3/library/distutils.html
- https://www.python.org/dev/peps/pep-0632/

**Comment by akx** [comment]
Thanks for the heads-up.

Yes, Babel will likely work with Python 3.12 – we'll likely excise the `distutils` compatibility stuff by then.

**Comment by RosanneZe** [comment]
Is this the same issue that causes the `SetuptoolsDeprecationWarning` when using the distutils/setuptools integration? I looked into using the cli instead of the integration, but that doesn't seem to pick up the configuration options I now have in a setup.cfg file (`[extract_messages]`, `[init_catalog]` etc).

**Comment by akx** [comment]
@RosanneZe What warning is that in particular?

**Comment by RosanneZe** [comment]
@akx This warning:
`.venv/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.`

**Comment by akx** [comment]
@RosanneZe That seems like an unrelated issue. Can you maybe open a new issue about it with a better repro case?

**Comment by akx** [comment]
With #835, Setuptools is used as the first preference, and distutils is the fallback. 

A future version of Babel will likely drop the fallbacks.

Thanks for the heads-up, @RomainBrault!
