### ISSUE TITLE
Babel does not support Kurdish locale 'ku'

### ISSUE THREAD

**Issue by olipeno** [python-babel/babel#83]
I am working on internationalization and need to support Kurdish language.

but when i run the following command to generate .po file for ku, I get the following error:

python setup.py init_catalog -l ku
running init_catalog
error: unknown locale 'ku'

>>> Locale('ku')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/webapp/responseweb/local/lib/python2.7/site-packages/Babel-1.3-py2.7.egg/babel/core.py", line 150, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'ku'

**Comment by smn** [comment]
Having the same issue for `kur`:

```python
>>> from babel import Locale
>>> Locale.parse('kur_IQ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sdehaan/Desktop/test/ve/lib/python2.7/site-packages/babel/core.py", line 315, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'kur_IQ'
>>> babel.__version__
'2.1.1'
>>>
```

**Comment by sils1297** [comment]
FWIW

> @smn could you try loading in `ku`?

> no, I tried that. Also not working.

I.e. this issue still applies for Babel 2.

**Comment by smn** [comment]
It looks like there's nothing around Kurdish in the CLDR zip file that's made available by the Unicore consortium:

```bash
$ find ./ -iname '*iq*'
.//common/main/ar_IQ.xml
```

```bash
$ find ./ -iname '*ku*'
``` 

Any suggestions on who to poke to get this addressed?

**Comment by etanol** [comment]
Once again, this is a CLDR issue, not a Babel one.  Out of curiosity, [I asked about it](http://unicode.org/pipermail/cldr-users/2015-September/000363.html) and [the answer](http://unicode.org/pipermail/cldr-users/2015-September/000364.html) was that the Northern Kurdish is not mature enough to be considered usable.

Please, feel free to contribute directly to CLDR in order to get Northern Kurdish officially complete.  Whenever this happens, the next time Babel updates the CLDR source, the `ku` locale will automatically appear.

**Comment by smn** [comment]
Thanks for the feedback.

**Comment by mardy** [comment]
Could someone please reopen this issue?

The CLDR 34 contains:
```
$ find . -iname '*ku*'
./collation/ku.xml
./main/ku_TR.xml
./main/ku.xml
./annotations/ku.xml
```
Yet these are not present in babel. I'm actually interested in the Interlingua locale (`ia`), which seems to share the same fate: there some files about it in the LCDR, but it's not supported in babel.
